# Generated by Django 2.2.1 on 2019-05-15 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apis',
            old_name='product',
            new_name='Product',
        ),
    ]
